### ISSUE TITLE
Subgraph isn't synchronized with onchain state leading to transaction failures

### ISSUE THREAD

**Issue by JSeam2** [zestymarket/bid-bot#3]
Thegraph subgraph is not always synchronized with onchain state leading to transaction failures.

Example. A bid was placed onchain however the subgraph has not synced. 

Traceback
```
An Exception has occured:  execution reverted: ZestyMarket_ERC20_V1::sellerAuctionBidBatch: Already has a bid
Traceback (most recent call last):
  File "main.py", line 66, in run
    self.act()
  File "main.py", line 55, in act
    self.processed_data = self.strategy.act(self.processed_data)
  File "DummyStrategy.py", line 92, in act
    gas_amount = txn_buy.estimateGas() + 100000
  File "miniconda3/envs/bidbot/lib/python3.8/site-packages/web3/contract.py", line 1039, in estimateGas
    return estimate_gas_for_function(
  File "miniconda3/envs/bidbot/lib/python3.8/site-packages/web3/contract.py", line 1620, in estimate_gas_for_function
    return web3.eth.estimate_gas(estimate_transaction, block_identifier)
  File "miniconda3/envs/bidbot/lib/python3.8/site-packages/web3/eth.py", line 825, in estimate_gas
    return self._estimate_gas(transaction, block_identifier)
  File "miniconda3/envs/bidbot/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "miniconda3/envs/bidbot/lib/python3.8/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "miniconda3/envs/bidbot/lib/python3.8/site-packages/web3/manager.py", line 170, in formatted_response
    apply_error_formatters(error_formatters, response)
  File "miniconda3/envs/bidbot/lib/python3.8/site-packages/web3/manager.py", line 70, in apply_error_formatters
    formatted_resp = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File "miniconda3/envs/bidbot/lib/python3.8/site-packages/web3/_utils/method_formatters.py", line 576, in raise_solidity_error_on_revert
    raise ContractLogicError(response['error']['message'])
web3.exceptions.ContractLogicError: execution reverted: ZestyMarket_ERC20_V1::sellerAuctionBidBatch: Already has a bid
```

**Comment by JSeam2** [comment]
The temporary fix is to catch the web3.exception.ContractLogicError.

The dummy strategy forgot to account for pending approval auctions, a clause was introduced to account for that.
