### ISSUE TITLE
Timeout too Short

### ISSUE THREAD

**Issue by JSeam2** [zestymarket/bid-bot#5]
# Issue 
wait_for_transaction_receipt requires a longer time out. The transaction got published but the bot crashed.

https://polygonscan.com/tx/0xdb8efc877097193a4256481f803760acf22c500a506396c7d6bedb8cda7705ab

# Traceback and Additional Information
```
An Exception has occured:  Transaction HexBytes('0xdb8efc877097193a4256481f803760acf22c500a506396c7d6bedb8cda7705ab') is not in the chain after 120 seconds
Traceback (most recent call last):
  File "/Users/jseam/miniconda3/envs/bidbot/lib/python3.8/site-packages/web3/eth.py", line 740, in wait_for_transaction_receipt
    _timeout.sleep(poll_latency)
  File "/Users/jseam/miniconda3/envs/bidbot/lib/python3.8/site-packages/web3/_utils/threads.py", line 89, in sleep
    self.check()
  File "/Users/jseam/miniconda3/envs/bidbot/lib/python3.8/site-packages/web3/_utils/threads.py", line 82, in check
    raise self
web3._utils.threads.Timeout: 120 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 67, in run
    self.act()
  File "main.py", line 56, in act
    self.processed_data = self.strategy.act(self.processed_data)
  File "/Users/jseam/Blockchain/ZestyMarket/bid-bot/strategies/DummyStrategy.py", line 111, in act
    txn_receipt = self.w3.eth.wait_for_transaction_receipt(txn_hash)
  File "/Users/jseam/miniconda3/envs/bidbot/lib/python3.8/site-packages/web3/eth.py", line 744, in wait_for_transaction_receipt
    raise TimeExhausted(
web3.exceptions.TimeExhausted: Transaction HexBytes('0xdb8efc877097193a4256481f803760acf22c500a506396c7d6bedb8cda7705ab') is not in the chain after 120 seconds
```

**Comment by JSeam2** [comment]
To revisit in future closing for now
